---
name: Build and Deploy React App to GitHub Pages
on:
  push:
    branches: [ master ]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: npm install

    - name: Test
      run: npm run test

    - name: Deploy
      run: |
        git config --global user.name 'Md Arifuzzaman'
        git config --global user.email 'md.arifuzzaman@mail.citytech.cuny.edy'
        git remote set-url origin https://github.com/mdarifuzzaman11/clevvar.git-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}    
        npm run deploy
